spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}


---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:~/test;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      auto-commit: false
      maximumPoolSize: 10


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/batch_study
      username: tester
      password: tester
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: never




