spring:
  profiles:
    active: mysql
  batch:
    job:
      names: ${job.name:NONE}


---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/batch_study
      username: tester
      password: tester
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: never




